import { TrackSchema, UserSchema } from "@/types/schemas";
import { Sharing } from "@/types/util";

export type PlaylistSchema = {
  kind: "playlist";
  title: string;
  urn: string;
  artwork_url: string;
  created_at: string;
  description: string;
  downloadable: string;
  duration: number;
  ean: string;
  embeddable_by: string;
  genre: string;
  label_id: number;
  label_name: string;
  last_modified: string;
  license: string;
  permalink: string;
  permalink_url: string;
  playlist_type: string;
  purchase_title: string;
  purchase_url: string;
  release: string;
  release_day: number;
  release_month: number;
  release_year: number;
  sharing: Sharing;
  streamable: boolean;
  tag_list: string;
  track_count: number;
  tracks: TrackSchema[];
  type: string;
  uri: string;
  user?: UserSchema;
  user_urn: string;
  likes_count: number;
  label?: UserSchema;
  tracks_uri?: string;
  tags?: string;
};
