import type { ResourceAccess, Sharing } from "@/types/util";
import type { UserSchema } from "./user.schema";

export type TrackSchema = {
  kind: "track";
  title: string;
  id: number;
  artwork_url: string;
  bpm: number;
  comment_count: number;
  commentable: boolean;
  created_at: string;
  description: string;
  download_count: string;
  downloadable: boolean;
  duration: number;
  favoritings_count: number;
  genre: string;
  urn: string;
  isrc: string;
  key_signature: string;
  label_name: string;
  license: string;
  metadata_artist?: string;
  permalink_url: string;
  playback_count: number;
  purchase_title: string;
  purchase_url: string;
  release: string;
  release_day: number;
  release_month: number;
  release_year: number;
  sharing: Sharing;
  streamable: boolean;
  tag_list: string;
  uri: string;
  user?: UserSchema;
  user_favorite: boolean;
  user_playback_count: number;
  waveform_url: string;
  available_country_codes: string;
  access: ResourceAccess;
  stream_url: string;
  download_url: string;
  reposts_count: number;
  secret_uri: string;
};
